language: node_js
sudo: true
dist: xenial
node_js:
- '10.11'
before_script: npm install -U npm
script: npm run build
notifications:
  email:
    on_failure: change
  webhooks: https://outlook.office.com/webhook/bba8187b-2198-46bb-adf5-dca60d4fbb1d@c845b8fa-0078-426b-8679-0da9f5eb0eed/TravisCI/a26937dbfb7948f5949f833416a1911a/1b4ab707-7048-4474-8611-7109f10acef8
