language: node_js
sudo: true
dist: xenial
node_js:
- '8.3'
before_script: npm install -U npm
script: npm run build
notifications:
  email:
    on_failure: change
  slack:
    secure: KoGNFUnoDzwPxBV8WnXU+XoihHhNQGkspYOvgnSZha+Ta6+nFbIiHai1K/F0QddT43aElQk9ko7nL5aLO2GTQzlBvgmJIYniQznurhe0FLBttGWqj7A/PjfVuyF6MlBYk62fP0zKT/KBDAU1jr4ox00GCkbFHxHle0aeeDI+mD7xZV8ImB4fr6f9OI65WpLQrNWRPYFfEuYN0EPxq4MaBv3f8CGJtXL8+VCN2gZcqVDA4UEjHQ9QwWKhUdLxeRyD9fH5h13TxG+84UXHVtKRoYolj1uruqur0NrS+5lj+JZM1ZBmvFvYnvDbC0kYOR+T1A0lD4pr0Wnz++nlafz6MxGhn1bgcxOwJogvOv4nnZRaBVgYVRMCe1RBlu8hQvsrdsqGbXEcckdlJWeCzfvEs3yuf1UOcvA44WLsGLqicwtORXktiRjR7CpL2JnoTNV5xyzC53rfDz3jbS5QhrdLa/y047JgpC5xnAnJEj6d53mmQqY7I4BOaxLcovSqcNsqoI1LdhVCNPVYqQttcgQuCf3IDXwW7v+5OKs9Q+dYxqwxll4/g3C86rJtNZFUz8ybVc46WyK+8ddbVkFj1AD0cIVwqN7jlUEaPDKgAf67txeQeE7+05a7cWUafQxgx1153p02r9/UL98cw/OjLsS/zMS9SnqrTv+E5+8twHYwwSU=
